export const SET_ACTIVE_STEP = "applyloan/SET_ACTIVE_STEP";

export const BUSINESS_LOAN_HEADINGS = "applyloan/BUSINESS_LOAN_HEADINGS";
export const BUSINESS_LOAN_HEADINGS_SET_DATA = "applyloan/BUSINESS_LOAN_HEADINGS_SET_DATA";

export const SAVE_COMPANY_DOCUMENTS = "applyloan/SAVE_COMPANY_DOCUMENTS";
export const SAVE_COMPANY_DOCUMENTS_SET_DATA = "applyloan/SAVE_COMPANY_DOCUMENTS_SET_DATA";

export const SAVE_COMPANY_DETAILS = "applyloan/SAVE_COMPANY_DETAILS";
export const SAVE_COMPANY_DETAILS_SET_DATA = "applyloan/SAVE_COMPANY_DETAILS_SET_DATA";

export const SAVE_KEY_MANAGEMENT_PERSONS = "applyloan/SAVE_KEY_MANAGEMENT_PERSONS";
export const SAVE_KEY_MANAGEMENT_PERSONS_SET_DATA = "applyloan/SAVE_KEY_MANAGEMENT_PERSONS_SET_DATA";

export const SAVE_FINANCIAL_DOCS = "applyloan/SAVE_FINANCIAL_DOCS";
export const SAVE_FINANCIAL_DOCS_SET_DATA = "applyloan/SAVE_FINANCIAL_DOCS_SET_DATA";

export const SAVE_BUSINESS_PLAN = "applyloan/SAVE_BUSINESS_PLAN";
export const SAVE_BUSINESS_PLAN_SET_DATA = "applyloan/SAVE_BUSINESS_PLAN_SET_DATA";

export const CLEAR_MESSAGE_OF_SAVE_COMPANY_DETAILS = "applyloan/CLEAR_MESSAGE_OF_SAVE_COMPANY_DETAILS";
export const CLEAR_MESSAGE_OF_SAVE_COMPANY_DOCS = "applyloan/CLEAR_MESSAGE_OF_SAVE_COMPANY_DOCS";
export const CLEAR_MESSAGE_OF_KMP = "applyloan/CLEAR_MESSAGE_OF_KMP";
export const CLEAR_MESSAGE_OF_FINANCIAL_DOCS = "applyloan/CLEAR_MESSAGE_OF_FINANCIAL_DOCS";
export const CLEAR_MESSAGE_OF_BUSINESS_PLAN = "applyloan/CLEAR_MESSAGE_OF_BUSINESS_PLAN";
export const CLEAR_MESSAGE_OF_SUBMIT_AND_VERIFY_DATA = "applyloan/CLEAR_MESSAGE_OF_SUBMIT_AND_VERIFY_DATA";

export const SUBMIT_AND_VERIFY_ALL_FIELDS = "applyloan/SUBMIT_AND_VERIFY_ALL_FIELDS";
export const SUBMIT_AND_VERIFY_ALL_FIELDS_SET_DATA = "applyloan/SUBMIT_AND_VERIFY_ALL_FIELDS_SET_DATA";

export const USER_BUSINESS_LOAN_DATA = "applyloan/GET_USER_BUSINESS_LOAN_DATA";
export const USER_BUSINESS_LOAN_DATA_SET_DATA = "applyloan/USER_BUSINESS_LOAN_DATA_SET_DATA";
